name: Publish

on:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Publication Package to Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Install Dependencies
        run: rye sync
      - name: Publish Package to Pypi
        run: make publish
