name: pytest

on:
  pull_request:
    branches:
      - develop

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rye
        uses: sksat/setup-rye@v0.8.0
      - name: Install Dependencies
        run: rye sync
      - name: Lint
        run: make lint
      - name: Test
        run: rye run pytest --cov=./slack_api_decorator --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
