name: pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rye
        uses: sksat/setup-rye@v0.8.0
      - name: Install Dependencies
        run: rye sync
      - name: Lint
        run: make lint
      - name: Test
        run: rye run pytest --cov --cov-report=xml
      - name: Code coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: codecov-umbrella
